name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Build
      run: |

        GOOS=linux GOARCH=amd64 make compile
        tar -czvf satisfy_linux-amd64.tar.gz workspace/*

        GOOS=darwin GOARCH=amd64 make compile
        tar -czvf satisfy_darwin-amd64.tar.gz workspace/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: satisfy_linux-amd64.tar.gz
        asset_name: satisfy_linux-amd64.tar.gz
        asset_content_type: application/tar+gzip

    - name: Upload Release Asset (Darwin)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: satisfy_darwin-amd64.tar.gz
        asset_name: satisfy_darwin-amd64.tar.gz
        asset_content_type: application/tar+gzip
